config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :categories 
  resources :expenses

  # root "categories#index"
  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_expenses
  has_many :expenses, through: :category_expenses
  has_one_attached :icon

  validates :name, presence: { allow_blank: false, message: 'must not be blank.' }
end

app/models/category_expense.rb
class CategoryExpense < ApplicationRecord
  belongs_to :expense, optional: true
  belongs_to :category, optional: true

  validates :expense_id, presence: { allow_blank: false, message: 'must not be blank.' }
  validates :category_id, presence: { allow_blank: false, message: 'must not be blank.' }
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user
  has_many :category_expense
  has_many :categories, through: :category_expense
  accepts_nested_attributes_for :category_expense

  validates :name, presence: { allow_blank: false, message: 'must not be blank.' }
  validates :amount, comparison: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :expenses
  has_many :categories
  validates :name, presence: { allow_blank: false, message: 'must not be blank.' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :redirect_to_hompeage, only: %i[index show]

  def redirect_to_hompeage
    redirect_to root_path unless user_signed_in?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.includes(:expenses).where(user_id: current_user.id)
  end

  def show
    @category = Category.includes(:expenses).find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.user = current_user

    if @category.save
      flash[:success] = 'Category added'
      redirect_to categories_path(id: params[:id])
    else
      flash.now[:error] = 'Category could not be saved'
      render :new
    end
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index; end

  def show; end

  def new
    @expense = Expense.new
    @expense.category_expense.build
  end

  def create
    permits = expense_params
    @expense = Expense.new(name: permits[:name], amount: permits[:amount])
    @expense.user_id = current_user.id
    flash.now[:error] = 'Expense could not be added' unless @expense.save
    category_id = permits[:category_expense_attributes]['0'][:category_id]
    @cat_exp = CategoryExpense.new
    @cat_exp.expense_id = @expense.id
    @cat_exp.category_id = category_id
    if @cat_exp.save
      flash[:success] = 'Expense added'
      redirect_to category_path(id: category_id)
    else
      flash.now[:error] = 'Expense could not be added'
    end
  end

  def expense_params
    params.require(:expense).permit(:name, :amount, category_expense_attributes: [:category_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :redirect_to_hompeage
  before_action :redirect_logged_user

  def redirect_logged_user
    redirect_to categories_path if user_signed_in?
  end

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/categories/index.html.erb
<%= 
  render "shared/navigation",
  nav_title: 'Categories',
  route_to: nil
%>

<% total_expenses = 0 %>
<% @categories.each do |cat| %>
  <% cat.expenses.each do |expense| %>
    <% total_expenses += expense.amount %>
  <% end %>
<% end %>

<section class="total-header">
  <h3>
    Total expenses
  </h3>
  <span>
    $<%= total_expenses.round(2) %>
  </span>
</section>

<ul class="categories-container">
  <% @categories.each do |category| %>
    <li class="category-card">
      <%= link_to(category_path(id: category.id)) do %>
        <div class="category-icon">
          <% if category.icon.attached? %>
            <img
              src="<%= url_for(category.icon) %>" 
              alt="<%= category.name %>"
            />
          <% end %>
        </div>
        <div class="category-title">
          <h4>
            <%= category.name %>
          </h4>
        </div>
        <div class="total-spent">
          <% total = 0 %>
          <% category.expenses.each do |exp| %>
            <% total += exp.amount %>
          <%end%>
          <h5>
            TOTAL
          </h5>
          <span>
            $<%= total.round(2) %>
          </span>
        </div>
      <% end %>
    </li>
  <% end %>
</ul>

<section class="button-container">
  <%= link_to("New Category", new_category_path, class: 'button btn-accept') %>
</section>

app/views/categories/new.html.erb
<%= 
  render "shared/navigation",
  nav_title: 'New Category',
  route_to: categories_path
%>

<section class="form-container">
  <%= form_for(@category) do |form| %>
    <%= form.file_field :icon, accept: 'image/png, image/jpg', required: true %>
    <%= form.label :icon, "Browse Icon", class: 'icon-input' %>

    <div class="form-fields">
      <%= form.text_field :name, placeholder: 'Name', required: true %>
    </div>

    <div class="button-container fixed-bottom">
      <%= form.submit "Add Category", class: 'button btn-accept' %>
    </div>
  <% end %>
</section>

app/views/categories/show.html.erb
<%= 
  render "shared/navigation",
  nav_title: @category.name,
  route_to: categories_path
%>

<section class="category-header">
  <div class="category-icon">
    <% if @category.icon.attached? %>
      <img
        src="<%= url_for(@category.icon) %>" 
        alt="<%= @category.name %>"
      />
    <% end %>
  </div>
  <h2>
    <%= @category.name%>
  </h2>
</section>

<section class="total-header">
  <h3>
    Total expenses
  </h3>
  <span>
    <% total = 0 %>
    <% @category.expenses.each do |expense| %>
      <% total += expense.amount %>
    <% end %>
    $<%= total.round(2) %>
  </span>
</section>

<section class="expenses-container">
  <ul>
    <% @category.expenses.each do |expense| %>
      <li class="expense-card">
        <h4>
          <%= expense.name %>
        </h4>
        <span>
          $<%= expense.amount.round(2) %>
        </span>
      </li>
    <% end %>
  </ul>

</section>

<section class="button-container">
  <%= link_to("Add expense",  new_expense_path(from: @category.id), class: 'button btn-accept') %>
</section>

app/views/expenses/new.html.erb
<% if params.has_key?(:from) %>
  <% previous_page = category_path(id: params[:from]) %>
<% else %>
  <% previous_page = root_path %>
<% end %>

<%= 
  render "shared/navigation",
  nav_title: 'New expense',
  route_to: previous_page
%>

<section class="form-container">
  <%= form_for(@expense) do |form| %>
    <div class="form-fields">
      <%= form.text_field :name, placeholder: 'Name' %>
      <%= form.number_field :amount, step: :any, placeholder: 'Amount' %>
    </div>
    <%= form.fields_for :category_expense do |cat_exp| %>
      <%= cat_exp.label :category_id %>
      <% categories_list = current_user.categories.map { |category| [category.name, category.id] } %>
      <%= cat_exp.select :category_id, categories_list, selected: params[:from] %>
    <% end %>
    <div class="button-container fixed-bottom">
      <%= form.submit "Add expense", class: 'button btn-accept' %>
    </div>
  <% end %>
</section>

app/views/home/index.html.erb
<section class="splash">
  <%= image_tag("static/wallist_logo.svg", alt: "Wallist") %>
</section>

<section class="home-wrapper">
  <div class="logo-container">
    <%= image_tag("static/wallist_logo_color.svg", alt: "Wallist") %>
  </div>
  <div class="buttons-container">
    <%= link_to "Log In", new_user_session_path, class: 'button btn-blue' %>
    <%= link_to "Sign Up", new_user_registration_path, class: 'button btn-secondary' %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_navigation.html.erb
<nav role="navigation">
  <div id="menu-toggle">
    <input id="menu-button" type="checkbox" />
    
    <% if route_to != nil %>
      <%= link_to(route_to) do %>  
        <div class="back-button">
          <span></span>
          <span></span>
          <span></span>
        </div>
      <% end %>
    <% end %>
    
    <div class="nav-title">
      <h2>
        <%= nav_title %>
      </h2>
    </div>
  
  <% if user_signed_in? %>
    <label for="menu-button"> 
      <span></span>
      <span></span>
      <span></span>
    </label>
    
    <ul id="menu">
      <a href="#">
        <li>
          <small>
            Hi <%= current_user.name %>
          </small>
        </li>
        </br>
      </a>
      <%= link_to categories_path do %>
        <li>Categories</li>
      <% end %>
      <%= link_to new_category_path do %>
        <li>Add category</li>
      <% end %>
      <%= link_to new_expense_path do %>
        <li>Add expense</li>
      <% end %>

      <%= button_to "Log out", destroy_user_session_path,  method: :delete %>
    </ul>
  <% end %>
  </div>
</nav>